"""add Department

Revision ID: 893fa7ee4daf
Revises: b61aa5fed24e
Create Date: 2025-01-14 10:28:53.921953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893fa7ee4daf'
down_revision = 'b61aa5fed24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
