"""rename department

Revision ID: ca79f7ecd6ed
Revises: 893fa7ee4daf
Create Date: 2025-01-14 10:32:27.035591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca79f7ecd6ed'
down_revision = '893fa7ee4daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')
    # ### end Alembic commands ###
